version: '3.9'
services:
  db:
    image: postgres:latest
    container_name: DwarfsDB
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "mydb"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 1s
  web-sockets:
    build:
      context: web-sockets
    ports:
      - "8001:8001"
    env_file: .env
    volumes:
      - ./web-sockets/:/app/
    depends_on:
      db:
        condition: service_healthy
  backend:
    build:
      context: .
      dockerfile: DockerfileBack
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./src:/app/src
      - ./uploads:/app/uploads
volumes:

  postgres_data: