"""init

Revision ID: c4efc94095f4
Revises: 
Create Date: 2024-04-29 08:48:58.092554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4efc94095f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('is_admin', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_category_id'), 'courses', ['category_id'], unique=False)
    op.create_index(op.f('ix_courses_id'), 'courses', ['id'], unique=False)
    op.create_index(op.f('ix_courses_name'), 'courses', ['name'], unique=True)
    op.create_table('course_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_tags_course_id'), 'course_tags', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_tags_id'), 'course_tags', ['id'], unique=False)
    op.create_index(op.f('ix_course_tags_text'), 'course_tags', ['text'], unique=False)
    op.create_table('lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lessons_course_id'), 'lessons', ['course_id'], unique=False)
    op.create_index(op.f('ix_lessons_id'), 'lessons', ['id'], unique=False)
    op.create_index(op.f('ix_lessons_name'), 'lessons', ['name'], unique=False)
    op.create_table('user_favorite_courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_favorite_courses_course_id'), 'user_favorite_courses', ['course_id'], unique=False)
    op.create_index(op.f('ix_user_favorite_courses_id'), 'user_favorite_courses', ['id'], unique=False)
    op.create_index(op.f('ix_user_favorite_courses_user_id'), 'user_favorite_courses', ['user_id'], unique=False)
    op.create_table('lesson_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_tests_id'), 'lesson_tests', ['id'], unique=False)
    op.create_index(op.f('ix_lesson_tests_lesson_id'), 'lesson_tests', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_lesson_tests_question'), 'lesson_tests', ['question'], unique=False)
    op.create_table('user_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_activity_id'), 'user_activity', ['id'], unique=False)
    op.create_index(op.f('ix_user_activity_is_completed'), 'user_activity', ['is_completed'], unique=False)
    op.create_index(op.f('ix_user_activity_lesson_id'), 'user_activity', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_user_activity_user_id'), 'user_activity', ['user_id'], unique=False)
    op.create_table('test_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('lesson_test_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_test_id'], ['lesson_tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_answers_answer'), 'test_answers', ['answer'], unique=False)
    op.create_index(op.f('ix_test_answers_id'), 'test_answers', ['id'], unique=False)
    op.create_index(op.f('ix_test_answers_is_correct'), 'test_answers', ['is_correct'], unique=False)
    op.create_index(op.f('ix_test_answers_lesson_test_id'), 'test_answers', ['lesson_test_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_answers_lesson_test_id'), table_name='test_answers')
    op.drop_index(op.f('ix_test_answers_is_correct'), table_name='test_answers')
    op.drop_index(op.f('ix_test_answers_id'), table_name='test_answers')
    op.drop_index(op.f('ix_test_answers_answer'), table_name='test_answers')
    op.drop_table('test_answers')
    op.drop_index(op.f('ix_user_activity_user_id'), table_name='user_activity')
    op.drop_index(op.f('ix_user_activity_lesson_id'), table_name='user_activity')
    op.drop_index(op.f('ix_user_activity_is_completed'), table_name='user_activity')
    op.drop_index(op.f('ix_user_activity_id'), table_name='user_activity')
    op.drop_table('user_activity')
    op.drop_index(op.f('ix_lesson_tests_question'), table_name='lesson_tests')
    op.drop_index(op.f('ix_lesson_tests_lesson_id'), table_name='lesson_tests')
    op.drop_index(op.f('ix_lesson_tests_id'), table_name='lesson_tests')
    op.drop_table('lesson_tests')
    op.drop_index(op.f('ix_user_favorite_courses_user_id'), table_name='user_favorite_courses')
    op.drop_index(op.f('ix_user_favorite_courses_id'), table_name='user_favorite_courses')
    op.drop_index(op.f('ix_user_favorite_courses_course_id'), table_name='user_favorite_courses')
    op.drop_table('user_favorite_courses')
    op.drop_index(op.f('ix_lessons_name'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_id'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_course_id'), table_name='lessons')
    op.drop_table('lessons')
    op.drop_index(op.f('ix_course_tags_text'), table_name='course_tags')
    op.drop_index(op.f('ix_course_tags_id'), table_name='course_tags')
    op.drop_index(op.f('ix_course_tags_course_id'), table_name='course_tags')
    op.drop_table('course_tags')
    op.drop_index(op.f('ix_courses_name'), table_name='courses')
    op.drop_index(op.f('ix_courses_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_category_id'), table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###